---
title: Prepare Variables for Mindfulness Intervention Study
author: Kyle M. Lang
date: 2021-09-01
output: html_document
---

```{r, include=FALSE}
options(width = 60)

## The following code will render scrollable text output when the `max-height`
## chunk option is set 
## (https://bookdown.org/yihui/rmarkdown-cookbook/hook-scroll.html)
local({
  hook_output <- knitr::knit_hooks$get('output')
  
  knitr::knit_hooks$set(
    output = function(x, options) {
      
      if (!is.null(options$max.height)) 
        options$attr.output <- c(
          options$attr.output,
          sprintf('style="max-height: %s;"', options$max.height)
        )
      
      hook_output(x, options)
    }
  )
})
```

First, we setup the environment and read in the data that we processed via the
SPSS recoding script.

```{r}
rm(list = ls(all = TRUE))

library(dplyr)

dataDir <- "../../../data/"
fn      <- "recoded_mindfulness_data-20210623.csv"

dat0 <- read.csv2(paste0(dataDir, fn))

head(dat0)
```

Now, we convert all categorical variables to factors.

```{r}
dat0$Interventiegroep <- factor(x      = dat0$Interventiegroep,
                                labels = c("control", "treatment")
                                )

dat0$marital_status_12 <- factor(x      = dat0$marital_status_12,
                                 levels = 1:5,
                                 labels = c("Getrouwd / samenwonend",
                                            "Relatie, maar niet samenwonend",
                                            "Gescheiden / uit elkaar",
                                            "Alleenstaand",
                                            "Anders")
                                 )

dat0$education_12 <- factor(x      = dat0$education_12,
                            levels = 1:6,
                            labels = c("Basisonderwijs",
                                       "VMBO / MAVO",
                                       "HAVO / VWO",
                                       "MBO",
                                       "HBO / WO",
                                       "Anders")
                            )

dat0$nationality_12 <- factor(x      = dat0$nationality_12,
                              levels = 1:2,
                              labels = c("Nederlandse", "Anders")
                              )

dat0$prev_miscarr_abort_12 <- factor(x      = dat0$prev_miscarr_abort_12,
                                     levels = 1:2,
                                     labels = c("Nee", "Ja")
                                     )

dat0$prev_childbirth_12 <- factor(x      = dat0$prev_childbirth_12,
                                  levels = 1:2,
                                  labels = c("Nee", "Ja")
                                  )

dat0$planned_pregnancy_12 <- factor(x      = dat0$planned_pregnancy_12,
                                    levels = 1:2,
                                    labels = c("Ja", "Nee")
                                    )

dat0$paid_work_12 <-
    factor(x      = dat0$paid_work_12,
           levels = 1:3,
           labels = c("Ja",
                      "Nee",
                      "Ja, maar momenteel werk ik langer dan 3 maanden niet")
           )

dat0$alcohol_12 <-
    factor(x      = dat0$alcohol_12,
           levels = 1:4,
           labels = c("Nee",
                      "Zo nu en dan, maar niet meer dan 1 glas per week",
                      "Ja, 2-4 glazen per week",
                      "Ja, meer")
           )

dat0$smoking_12 <- factor(x      = dat0$smoking_12,
                          levels = 1:2,
                          labels = c("Nee", "Ja")
                          )
```

Check the structure of our data set, so far.

```{r, max.height = "200px"}
str(dat0)
```
```{r}
## Convert gestatinal age from character to numeric:
dat0$Gestational_age_8wpp <- as.numeric(dat0$Gestational_age_8wpp)

tmp           <- dat0[grep("Gestational", colnames(dat0))]
colnames(tmp) <- c("raw", "week")

with(tmp, sum(is.na(raw) & !is.na(week)))
with(tmp, sum(is.na(week) & !is.na(raw)))

### Gestational_age_weeks_8wpp is a truncated version of Gestational_age_8wpp
### The former has less missing data than the latter, though.
### We can only use one, so we're better off going with the "weeks" version.

## Drop extraneous variables:
dat1 <- dat0[
    grep("name|date|age_weeks",
         colnames(dat0),
         ignore.case = TRUE,
         invert      = TRUE)
]

head(dat1)

### WE ONLY HAVE MINDFULNESS DATA FOR THE INTERVENTION GROUP, SO WE NEED TO
### SPLIT THE SAMPLE.

datList <- list()

## Data for only the intervention group:
datList$int <- dat1[dat1$Interventiegroep == "treatment", ]

## Combined data without mindfulness items:
datList$com <- dat1[grep("^TFMQ|^RRQ|^SCS", colnames(dat1), invert = TRUE)]

saveRDS(datList, paste0(dataDir, "datList.rds"))
```
